config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :patients, only: [:index, :show]
end

app/models/admission.rb
class Admission < ApplicationRecord
  has_many :diagnoses
  has_many :symptoms
  has_many :observations

  validates :moment, presence: true
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :patient, optional: true

  validates :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def date
    if defined?(self.moment)
      self.moment.to_date.to_formatted_s(:long)
    end
  end

  def time
    if defined?(self.moment)
      self.moment.strftime("%I:%M%p")
    end
  end

end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  belongs_to :patient_diagnosis, class_name: "Patient", optional: true
  belongs_to :chronic_condition, class_name: "Patient", optional: true
  belongs_to :admission, optional: true

  validates :description, :code, presence: true

  def described_code
    "#{self.description} (#{self.code})"
  end
end

app/models/diagnostic_procedure.rb
class DiagnosticProcedure < ApplicationRecord
  belongs_to :patient, optional: true

  validates :description, :moment, presence: true
end

app/models/facility.rb
class Facility < ApplicationRecord
  has_many :patients

  validates :name, presence: true
end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord
  belongs_to :order_frequency, optional: true
  belongs_to :patient, optional: true

  enum mass_unit: [:mg]
  enum medication_route: [:PO, :IM, :SC]

  validates :name, :mass_unit, :medication_route, :necessity, :dosage, presence: true

  def route
    self.medication_route
  end

  def frequency
    self.order_frequency.value
  end
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :admission

  validates :description, presence: true
end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord
  has_many :medication_orders
  enum frequency_unit: [:hour]

  validates :value, :frequency_unit,  presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :admission
  belongs_to :facility, optional: true

  has_many :allergies
  has_many :diagnoses, class_name: "Diagnosis", foreign_key: "patient_diagnoses_id"
  has_many :chronic_conditions, class_name: "Diagnosis", foreign_key: "chronic_condition_id"
  has_many :medications, class_name: "MedicationOrder"
  has_many :diagnostic_procedures
  has_many :treatments

  enum gender: [:male, :female, :other]

  def format_name
    self.first_name + " " + self.last_name
  end

  def age
    return if !self.dob?
    now = Time.now.utc.to_date
    now.year - self.dob.year - ((now.month > self.dob.month || (now.month == self.dob.month && now.day >= self.dob.day)) ? 0 : 1)
  end

  def format_medications
    return if !(self.medications.exists?)
    self.medications.map do |med|
      "#{med.name} #{med.dosage.to_i}#{med.mass_unit} #{med.route} #{med.frequency} to #{med.necessity}"
    end
  end

  def format_diagnostic_procedures
    return if !(self.diagnostic_procedures.exists?)
    self.diagnostic_procedures.map do |procedure|
      "#{procedure.description} on #{procedure.date} at #{procedure.time}"
    end
  end

  def format_treatments
    return if !(self.treatments.exists?)
    self.treatments.map { |treatment| "#{treatment.description} to #{treatment.necessity}" }
  end

end

app/models/symptom.rb
class Symptom < ApplicationRecord
  belongs_to :admission, optional: true

  validates :description, presence: true
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :patient, optional: true

  validates :description, :necessity, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def to_attributes_array(collection, attribute)
    collection.map { |instance| instance[attribute] }
  end

  def to_described_code(collection)
    collection.map { |instance| instance.described_code }
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmergencySummaryPrototype</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <br></br>
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/patients/_patient.html.erb
<div class="">
  <%= link_to patient.format_name, patient_path(patient) %>
</div>

app/views/patients/_patient_info.html.erb
<td>First Name <br> <p class="text-primary"> <%= @patient.first_name %> </p></td>
<td>Middle Name <br> <p class="text-primary"> <%= @patient.middle_name %> </p></td>
<td>Last Name <br> <p class="text-primary"> <%= @patient.last_name %> </p></td>
<td>Medical Record (MR) <br> <p class="text-primary"> <%= @patient.mr %> </p></td>

app/views/patients/_print.html.erb
<div class="pull-right">
  <a href="#" onclick="window.print();return false;">Print</a>
</div>

app/views/patients/_summary.html.erb
This <%= @patient.age %> years old <%= @patient.gender %> was admitted to <%= @patient.facility.name %> on <%= @patient.admission.date %> at <%= @patient.admission.time %> due to <%= to_attributes_array(@patient.admission.diagnoses, 'description').to_sentence %>. The observed symptoms on admission were <%= to_attributes_array(@patient.admission.symptoms, 'description').to_sentence %>. <%= to_attributes_array(@patient.admission.observations, 'description').to_sentence %>.

<br></br>

Upon asking about known allergies, the patient disclosed <%= to_attributes_array(@patient.allergies, 'description').to_sentence %>. Upon asking about chronic conditions, the patient disclosed <%= to_described_code(@patient.chronic_conditions).to_sentence %>. The patient was administered with <%= @patient.format_medications.to_sentence %>.

<br></br>

The staff performed <%= @patient.format_diagnostic_procedures.to_sentence %>, revealing <%= to_described_code(@patient.diagnoses).to_sentence %>. Our team proceeded to <%= @patient.format_treatments.to_sentence %>.

app/views/patients/index.html.erb
<h2>Emergency Transfer Patient List</h2>

<%= render @patients  %>

app/views/patients/show.html.erb
<div class="">
  <%= link_to 'Back', patients_path()%>

  <%= render partial: 'print' %>
</div>

<div class="panel panel-default">
  <!-- Panel Title -->
  <div class="panel-heading"><b>Emergency Transfer Summary (Form 34L-D)</b></div>

  <!-- Table -->
  <table class="table">
    <tr>
      <th colspan="4">Transferring Facility</th>
    </tr>
    <tr>
      <td colspan="4">
        Name <br>
        <p class="text-primary"><%= @patient.facility.name if @patient.facility %></p>
      </td>
    </tr>

    <tr>
      <th colspan="4">Patient Information</th>
    </tr>
    <tr>
      <%= render partial: 'patient_info', object: @patient %>
    </tr>

    <tr>
      <th colspan="4">Summary</th>
    </tr>
    <tr>
      <td colspan="4" class="text-primary">
        <%= render partial: 'summary', object: @patient  %>
      </td>
    </tr>
  </table>

</div>